### ISSUE TITLE
SqliteBuddy.GetField unhandled exception on null result

### ISSUE THREAD

**Issue by script-chimp** [richardperkins/Db-Buddy#2]
Passing in values for a field of a table throws an unhandled exception.

**Comment by richardperkins** [comment]
Fixed this issue in https://github.com/richardperkins/SqliteBuddy/commit/1a849ba49e48ce170db6c7e4121a517ec65d0daf

**Comment by script-chimp** [comment]
Fixed this issue in https://github.com/richardperkins/SqliteBuddy/commit/1a849ba49e48ce170db6c7e4121a517ec65d0daf
